# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: Fonksiyon Testleri ve PyPI Yükle

on: [push, pull_request]

jobs:
  KekikTest:
    name: Fonksiyon Testleri

    strategy:
      matrix:
        python-version: ["3.10.8"]
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v3

      - name: Python ${{ matrix.python-version }} Sürümü Yükleniyor
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Sürümünü Göster
        run : python -c "import sys; print(sys.version)"

      - name: Tesseract OCR Yükle
        run : |
          sudo apt-get update && sudo apt-get install tesseract-ocr

      - name: Pytest'i Yükle
        run : |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Kütüphaneyi Yükle
        run : pip install .

      - name: Test Dosyalarını Çalıştır
        run : pytest

      # - name: Test Dosyalarını Windows Ortamda Çalıştır
      #   if: matrix.os == 'windows-latest'
      #   shell: cmd
      #   run: |
      #     cd ${{ github.workspace }}/Testler
      #     FOR %%i in (*.py) DO python -m pytest %%i

      # - name: Test Dosyalarını Posix Ortamda Çalıştır
      #   if: matrix.os != 'windows-latest'
      #   run: pytest Testler/*



  PyPIYukleyici:
    name    : PyPI Yükleyici
    runs-on : ubuntu-latest
    needs   : KekikTest

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v3

      - name: Python 3.10.8 Yükle
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"

      - name: Python Sürümünü Göster
        run : python -c "import sys; print(sys.version)"

      - name: Gereksinimleri Yükle
        run : |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel build twine

      - name: Kütüphaneyi PyPI'ye Yükle
        env :
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run : |
          python -m build --sdist --wheel
          twine check dist/*
          python -m twine upload dist/*
          rm -rf build/ dist/ *.egg-info/